// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Step2Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void step2()
    {
        driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
        driver.Manage().Window.Size = new System.Drawing.Size(1089, 713);
        driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
        driver.FindElement(By.Id("signupName")).Click();
        driver.FindElement(By.Id("signupName")).SendKeys("Jhon");
        driver.FindElement(By.Id("signupLastName")).Click();
        driver.FindElement(By.Id("signupLastName")).SendKeys("Smith");
        driver.FindElement(By.Id("signupEmail")).Click();
        driver.FindElement(By.Id("signupEmail")).SendKeys("JSmith5@gml.com");
        driver.FindElement(By.Id("signupPassword")).Click();
        driver.FindElement(By.Id("signupPassword")).SendKeys("Js123456");
        driver.FindElement(By.Id("signupRepeatPassword")).Click();
        driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("Js123456");
        driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
        driver.FindElement(By.LinkText("Profile")).Click();
        {
            WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(30));
            wait.Until(driver => driver.FindElements(By.XPath("//p[@class=\"profile_name display-4\"]")).Count > 0);
        }
        var elements = driver.FindElements(By.XPath("//p[@class=\"profile_name display-4\"]"));
        Assert.True(elements.Count > 0);
        driver.FindElement(By.CssSelector(".sidebar > .btn:nth-child(1)")).Click();
        driver.FindElement(By.CssSelector(".btn-primary")).Click();
        driver.FindElement(By.Id("addCarModel")).Click();
        {
            var dropdown = driver.FindElement(By.Id("addCarModel"));
            dropdown.FindElement(By.XPath("//option[. = 'R8']")).Click();
        }
        driver.FindElement(By.Id("addCarMileage")).Click();
        driver.FindElement(By.Id("addCarMileage")).SendKeys("87");
        driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
        driver.FindElement(By.CssSelector(".car_add-expense")).Click();
        driver.FindElement(By.Id("addExpenseMileage")).SendKeys("120");
        driver.FindElement(By.Id("addExpenseLiters")).Click();
        driver.FindElement(By.Id("addExpenseLiters")).SendKeys("15");
        driver.FindElement(By.Id("addExpenseTotalCost")).Click();
        driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("5");
        driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
        driver.FindElement(By.LinkText("Settings")).Click();
        driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
        driver.FindElement(By.CssSelector(".btn-danger")).Click();
    }
}
